### ISSUE TITLE
Is there a way to specify browserify plugins to use? Specifically want to use browserify-HMT

### ISSUE THREAD

**Issue by cheapsteak** [mattdesl/budo#102]
This is nice
Want to use this for developing components (react and vue)
HMR is nice too, how would I get this working with browserify-hmr?

**Comment by mattdesl** [comment]
Anything after `--` gets passed to browserify options, so you can do this:

```sh
budo src/main.js:bundle.js -- -p browserify-hmr -t vueify
```

Example with vueify:
https://github.com/mattdesl/vueify-example/blob/0f90fa60d8f8aae0d173e00f19af8a768a2f8dfa/package.json#L7-L8

The hot reloading has some differences than Budo's typical live reloading (browser refresh). For example, you won't see `.vue` syntax errors until you manually refresh the page, since it's not triggered by the HMR. I think with some tweaks the experience could be better.

**Comment by cheapsteak** [comment]
Ahh that's perfect, thanks!
