### ISSUE TITLE
Support rollup?

### ISSUE THREAD

**Issue by tomekwi** [mattdesl/budo#109]
Hi, *budō* is fantastic!

And so is the latest and greatest https://git.io/rollup. Because the principles behind ES 2015 are simpler than those behind CommonJS, the generated bundles are [much cleaner](https://github.com/nolanlawson/rollup-comparison). I think it also has the potential of being an order of magnitude faster than CommonJS-based bundlers (though @Rich-Harris may want to correct me here).

It’d be great to have an option saying “spawn a custom build command” or “execute a custom JS build file”. Then we could opt out of *browserify* and replace it with *rollup* or *webpack*.

Is it at all possible? The API would likely get a bit heavier – is it worth it?

**Comment by Rich-Harris** [comment]
From Rollup's side, the thing that would make this worthwhile is incremental rebuilds, which we don't *yet* support (https://github.com/rollup/rollup/issues/191). Performance-wise I haven't really compared Rollup with Browserify (though I have found it to be a little bit faster than Webpack) so can't really speak to that – there is a performance penalty to using the [commonjs](https://github.com/rollup/rollup-plugin-commonjs) transformer (because modules need to be parsed twice – something we may hack around in future) so with or without incremental rebuilds it would probably only be faster with ES6-only projects, or those with only a few small commonjs deps.

**Comment by yoshuawuyts** [comment]
> This is a browserify development server inspired by beefy and wzrd

Though `rollup`'s tree shaking mechanism is definitely an interesting file-size optimization, I think it's best to remember that `budo` is focused on development. Given that `rollup` doesn't support incremental rebuilds (which makes it slow), adds a non-trivial amount of complexity to `budo` and well, isn't very relevant for budo's intended use case I'm :-1: on this.

If you want your final bundle to be generated by `rollup`, run the command before deploying and you should be good (':

Also fwiw: tree-shaking might be available for `browserify` soonish as a transform soonish, if it isn't already.

**Comment by mattdesl** [comment]
Budo is just for browserify; trying to include multiple incompatible bundlers in a single tool would add a great deal of bloat and complexity without much benefit. 

However, since budo is highly modular and many of its internal features are being split into independent modules, it should be possible to build a similar tool on top of a different bundler (like rollup, jspm, or webpack). :smile:

**Comment by tomekwi** [comment]
:+1: Thanks for all your feedback, guys!

**Comment by tomekwi** [comment]
I actually wanted to take a crack at this, but it turned out to be a lot more work than my little [*elm-live*](https://github.com/tomekwi/elm-live) (the only server I had written so far). And without incremental builds the thing would be slow anyway.

As we’re now in a hurry at our office, I went the quick but flawless way @yoshuawuyts has suggested. During development our modules are piped down *browserify* + *budō*, but the final bundle goes through *rollup*.

**Comment by veggiemonk** [comment]
Maybe this can help: https://github.com/nolanlawson/rollupify @tomekwi @mattdesl @Rich-Harris @yoshuawuyts

**Comment by yoshuawuyts** [comment]
oh, that's def cool - I'll def have to test it out. I don't think it should be part of `budo` core tho, as it doesn't add value when developing... but for production it would def be great! Perhaps we should mention it in the README (':

**Comment by veggiemonk** [comment]
@yoshuawuyts True that `rollup` is good production bundling which is definitely not in `budo` scope.

But again, if bundle size really matter, there might some more powerful alternative such as closure compiler. See https://github.com/samccone/The-cost-of-transpiling-es2015-in-2016

`budo + browserify` is the fatest, simplest way I found to quickly getting to write code for the app and not for the dev env/production bundling. Plus, the code can be easily adapted. PR are fast and easy, see #141

**Comment by kolya-ay** [comment]
Rollup meanwhile [got an incremental rebuilding](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0300) support.

**Comment by yaycmyk** [comment]
@mattdesl can this be reopened now that rollup supports incremental rebuilds? I'd love to have a blessed way to make use of it!

**Comment by yoshuawuyts** [comment]
@yaycmyk I'm still not convinced adding `rollup` to `budo` would be a good choice - it significantly complicates internals for no gain in development (file size on `localhost` isn't really an issue). When bundling for production tools like [bundleify](https://github.com/bendrucker/bundleify) or creating your own `browserify` step might make more sense

**Comment by mattdesl** [comment]
My thoughts are the same as in [my previous comment](https://github.com/mattdesl/budo/issues/109#issuecomment-160323279).

Rollup is great and I hope to see a "budo-like tool for rollup" (maybe using some of the same modules as budo) but I do not feel we should re-factor and bloat budo every time a new bundler becomes popular. Budo is designed *for browserify*, after all. :smile:
