### ISSUE TITLE
Support HTML preprocessors with command line interface

### ISSUE THREAD

**Issue by KevinGrandon** [mattdesl/budo#114]
It would be nice to have a way of supporting HTML preprocessors or templating libraries when using the budo command line interface.

E.g., I want to run something like a handlebars or jade command each time either when starting budo, or in the `--watch` command.

I couldn't easily find a way to do this with the current code, but if it exists then please use this issue to update docs.

**Comment by mattdesl** [comment]
In some projects I have used [hbsfy](https://github.com/epeli/node-hbsfy) which tends to handle file updates nicely since it's integrated into watchify.

If you use the CLI, you can run a shell command with `--onupdate`. If you use the API, you will have to set up watch globs and events correctly to get it working. 

I will leave this issue open for more discussion, as there might be some improvements that could be made to budo and/or its docs.

**Comment by mattdesl** [comment]
Closing since this seems OK. If anybody wants I will accept a PR with another example of this in the command line docs.
