### ISSUE TITLE
Option to clear the console on livereload in the browser

### ISSUE THREAD

**Issue by jimdebeer** [mattdesl/budo#154]
I really enjoy using budo, but I have one very small issue -- on livereload the console does not get cleared is this possible, or can this become a feature in the future?

**Comment by mattdesl** [comment]
I'm not sure I want to support this out of the box since it's a matter of taste/opinion (I prefer not to clear console) and also introduces some platform juggling to clear properly across different terminals.

However, it should already be possible with the API. You can create your own budo CLI like so:

`dev.js`

```js
var clear = require('clear');
var app = require('budo').cli(process.argv.slice(2));
var first = true;
if (app) {
  app.on('update', function () {
    if (!first) clear();
    first = false;
  });
}
```

Now, run the file with the same arguments you would budo:

```sh
node dev.js src/index.js:bundle.js --live
```

**Comment by jimdebeer** [comment]
thanks a lot! looks simple enough to not make it into an option

**Comment by jimdebeer** [comment]
I meant clearing the  console in the browser not in node 😄 -- is this trivial as well?

**Comment by yoshuawuyts** [comment]
Perhaps if you add this to your code?
```js
window.onload = function () {
  if (console.clear) console.clear()
}
```

**Comment by mattdesl** [comment]
The Chrome console should already be clearing on reload. Make sure you don't have "Preserve Log" checked.

**Comment by mattdesl** [comment]
Going to close since this isn't really an issue with budo.

**Comment by jimdebeer** [comment]
issue with chrome canary -- sorry about this!
