### ISSUE TITLE
chokidar and internal-ip

### ISSUE THREAD

**Issue by MattMcFarland** [mattdesl/budo#161]
Hi,
I love budo!  However I've noticed it takes a long time to install and these two repos have a huge amount of dependencies and make this a really heavy download, what are your thoughts on removing them?  

I dont need internal-ip and it uses a TON, but chokidar is almost worse.  I think chokidar could be replaced with a smaller watch script (are you using all the chokidar features??)  

internal-ip causes a lot of problems especially when behind a proxy.  I've never needed to use something like that, what is the use case?

Thanks!

**Comment by mattdesl** [comment]
I've never had issues installing budo and I do a fresh install on a near daily basis. How long does it take, and are you using the latest version of npm?

Chokidar is used by watchify (another dep) so removing it from budo won't really do anything except increase the potential for bugs and potentially remove some features users have come to depend on. Something we can do is try to use the same version as in watchify so that npm dedupes it.

Internal-ip is used for better UX, so users can just copy the IP they see in the console and it will work on all devices connected to the same network. If there is an alternative I might be open to changing the dependency. Also, I think we could improve the way the command is used internally to help some of your proxy issues. 

Thanks! 😊

**Comment by MattMcFarland** [comment]
Hi thanks for responding.  I'm not sure if the benefit of internal-ip is being used to the point it should be part of budo - shouldnt budo be more light weight?  However, I think the main problem I have is that it takes a long time to install, I am using node v6.3.0 and npm 3.x (latest version as of yesterday) and it takes a few minutes to install budo.  Then I have to use --host localhost or else it points at my ip address which is the last thing I want.

I really like budo and will continue to use it, however some of my colleagues complain about the size and time it takes to install.
