### ISSUE TITLE
Add `--gzip` option to serve compressed files

### ISSUE THREAD

**Issue by anandthakker** [mattdesl/budo#176]
@mattdesl would you be open to a PR adding a flag to serve gzipped files?

Reason: I've been using Chrome's network speed throttling while developing, and there's often a rather large difference in the gzipped vs uncompressed bundle size, making the initial load painfully slow.

**Comment by mattdesl** [comment]
Sure!

**Comment by mattdesl** [comment]
I've been testing with the following which seems to work pretty well:

```js
// dev.js
const compression = require('compression')
require('budo').cli(process.argv.slice(2), {
  middleware: compression()
})
```

You can then treat it like a budo script:

```sh
node dev.js index.js:bundle.js --live -- -t babelify
```

However, in my tests everything actually seems a little slower, perhaps because the cost of inflate/deflate outweighs the benefits of a smaller payload on a local server. I'm curious to test some cases where gzip improves performance. Maybe it makes the most sense for mobile development over WiFi. :smile:

**Comment by mattdesl** [comment]
I am going to close for now since this is easy enough for a dev to add with a custom script, and doesn't seem to have a huge benefit on localhost.
