### ISSUE TITLE
babelHelpers is not defined

### ISSUE THREAD

**Issue by AlexandreBonaventure** [mattdesl/budo#185]
Hi,
my package : 
```    
"babel-plugin-external-helpers": "^6.8.0",
"babel-preset-es2015": "^6.18.0",
"babelify": "^7.3.0",
"babelify-external-helpers": "^1.1.0",
"budo": "^9.2.2",
```

I wanted to apply a babelify transform to my bundle so I ran budo like in the example:
``budo examples/simple/index.js --open -d . --live -- -t [ babelify --presets [ es2015 ] ]``

In my ChromeDev Tool I was experiencing this issue : babelHelpers is not defined.

I fixed the problem by installing `babelify-external-helpers`, and run it like: 
``budo examples/simple/index.js --open -d --live -- -t [ babelify --presets [ es2015 ] --plugins [external-helpers-2] --sourceType module] -p [ babelify-external-helpers ]``

ps: great package by the way, love it !

**Comment by mattdesl** [comment]
Are you running `budo` directly from the command-line? That will run a globally-installed version of budo. It can be handy for quick prototyping but you'll run into problems like this on real projects.

Instead, you should make sure you're running the *locally installed* version of budo, so that transforms can resolve presets correctly. Something like this in your package.json:

```js
  "scripts": {
    "start": "budo examples/simple/index.js --open --live -- -t [ babelify --presets [ es2015 ] ]"
  } 
```

Then, from command line:

```sh
npm run start
```

**Comment by mattdesl** [comment]
Going to close due to inactivity. Thanks.
