### ISSUE TITLE
Silent failure with existing `index.html` file?

### ISSUE THREAD

**Issue by jnj16180340** [mattdesl/budo#193]
The command:  
`node node_modules/budo/bin/cmd.js index.js --live --open --wg *.js`  

With this directory structure, budo serves `index.html` from the root directory and does not rebuild `bundle.js` in the root directory.
````
.
├── index.js
├── bundle.js # manually generated by browserify
├── index.html # Loads ./bundle.js
├── node_modules/
└── more stuff...
````

With `index.html` renamed, budo serves the correct `index.html` and `bundle.js` files, e.g. the ones it generated.
````
.
├── index.js
├── bundle.js # manually generated by browserify
├── outdex.html # Renamed from index.html
├── node_modules/
└── more stuff...
````

Using `--dir`, e.g. `node node_modules/budo/bin/cmd.js index.js --live --open --dir build-demo --wg *.js` works fine even with an existing `index.html`, but it took me a little while to figure out the problem in the first place.

Is this expected behavior, and would it be helpful to add a warning "Using existing `index.html` at ..." or something like that?

**Comment by mattdesl** [comment]
Thanks, I can reproduce this on my end so I'll see what I can do about fixing it. :smile:

**Comment by mattdesl** [comment]
Oh — maybe I'm mistaken. I am testing with your command and the same directory structure, and it's reloading the browser page. However, because the `index.html` is pointing to `<script src="bundle.js">`, any changes to the `index.js` will not be reflected in the newly reloaded page.

Instead, you should try this:

- Use `budo index.js:bundle.js` or `budo index.js --serve bundle.js` to indicate that the bundle will be located at `bundle.js`
- OR change your `index.html` script to point to `index.js`

I would recommend the former since it's a clearer separation of dev/prod scripts, and when you go to publish your static site online you won't need to change the `index.html` source if it already points at `bundle.js`.

Also, you shouldn't need to `--wg *.js` — the root index (that you are browserifying) should be live-reloaded, as are CSS and HTML files. You only need to add watch globs for other files, e.g. if you have a `<script src="vendor.js">` before your bundle, you might want to include that in the watch glob.

Let me know if I'm misunderstanding this problem. If you could create a repository that shows it more succinctly it might help me narrow it down.

**Comment by jnj16180340** [comment]
>  However, because the `index.html` is pointing to `<script src="bundle.js">`, any changes to the `index.js` will not be reflected in the newly reloaded page

Yeah, that was it... oops. Thanks for pointing it out.
