### ISSUE TITLE
browser requests at wrong path

### ISSUE THREAD

**Issue by sladiri** [mattdesl/budo#209]
Hi, I am not sure, if this is a Budo issue or a Babel issue. The whole project is here: https://github.com/sladiri/browser-boiler
While the main script file is loaded fine, the browser then requests a Babel polyfill file from the wrong path (404):
`http://localhost:9966/dist/node_modules/core-js/library/modules/es6.object.to-string.js`
This should probably be (without `dist`):
`http://localhost:9966/node_modules/core-js/library/modules/es6.object.to-string.js`

I work around this by creating a symlink in `dist/` to `node_modules/`

start npm script: `budo src/main.js:dist/bundle.js --pushstate --live -- -t babelify`

index.html:
```
<!doctype html>
<html lang=en>

<head>
  <base href="/">
  <meta charset=utf-8>
  <title>Browser Boiler</title>
</head>

<body>
  <div id="app"></div>
  <script src="dist/bundle.js"></script>
```
.babelrc:
```
{
  "plugins": [
    [
      "transform-runtime",
      {
        "helpers": true,
        "polyfill": false,
        "regenerator": false,
        "moduleName": "babel-runtime"
      }
    ],
    "transform-es2015-modules-commonjs",
    "transform-object-rest-spread",
    "transform-async-to-generator",
    "transform-async-generator-functions",
    "syntax-trailing-function-commas",
    "transform-function-bind"
  ],
  "presets": [],
  "sourceMaps": true,
  "retainLines": true
}
```

**Comment by mattdesl** [comment]
Your project seems to work for me in Chrome DevTools:

<img width="776" alt="screen shot 2017-05-10 at 3 36 29 pm" src="https://cloud.githubusercontent.com/assets/1383811/25917550/7d7ed574-3596-11e7-867a-90097d83a634.png">

It's looking for `/dist` since that's the path being used for your JS bundle. But DevTools actually finds the file in `node_modules/...` (no `dist` folder).

Where does that URL with node_modules come from? You probably don't want to ever hit a node_module directly via a URL like this:

`http://localhost:9968/node_modules/core-js/library/modules/es6.object.to-string.js`

The only reason the above isn't 404ing is because budo is serving the whole current working directory, so it also serves static files (including JS files) in other folders within your current working directory.

Generally I like to organize my static sites with an `app/` folder which holds the bundle, CSS and HTML file. The `node_modules` doesn't need to be served at all since everything is bundled into your single JS file.

Here is an example of my setup:
https://github.com/mattdesl/raylight/blob/6bc8f90f22fe97f87b58ad8efc6063805e276828/package.json#L81-L85

**Comment by sladiri** [comment]
The URL was not from me directly, it looked, like a babel-polyfill looked for the file, and that the bundle was somehow incomplete, as you suggested.

However, the error is gone now. Thank you for the help. I can run the project without issue, I am not sure, what changed unfortunately.
