### ISSUE TITLE
Outfile option not being passed to Browserify.

### ISSUE THREAD

**Issue by ootoovak** [mattdesl/budo#31]
Hi, so I know you have taken out the `--outfile` option from Budo in v3.0 (curious as to why?) but is there anyway to keep passing that option to Browserify? I have tried `budo app/app.js:index.js -- -t babelify -o index.js` but that does not seem to work. Thanks for any insight you can provide.

**Comment by mattdesl** [comment]
budo@3.0 just serves the bundle in memory, and doesn't do any file read/write operations. 

Adding `--outfile` would lead to a lot of code complexity and a divergence from the current behaviour. The argument was also confusing since the browserify option is relative to their `process.cwd()`.

What are your use cases for `--outfile`? If you are looking for a production build, I tend to use `browserify` since watchify was never intended for that task.

```js
"scripts": {
    "start": "budo index.js:bundle.js --live -v | garnish",
    "build": "browserify index.js | uglifyjs -cm > bundle.js"
}
```

**Comment by ootoovak** [comment]
@mattdesl yeah it was for a deploy (not really "production") build. My use case was for toy applications, quick development and deploy, and I kept forgetting to do the build step before a deploy when using Beefy :stuck_out_tongue: so pre Budo v2.x worked for me with that for a while. That said I can see that it is a small subset problem and most of the time you would want a build step for production deploys to also include things like `uglifyjs`. I think if I do a compound step of sorts:
```
"scripts": {
  "start": "budo index.js:bundle.js --live -v | garnish",
  "build": "browserify index.js | uglifyjs -cm > bundle.js",
  "commit": "npm run build && git add index.js && git commit -m "Generated production static file."
  "push": "npm run commit && git push origin master",
  "deploy": "npm run commit && git push dokku master" 
}
```
Thanks for taking the time to explain why you don't have that in Budo anymore and the possible solution.
