### ISSUE TITLE
Budo does not browserify a file if specify the entry with base directory. 

### ISSUE THREAD

**Issue by nxxcxx** [mattdesl/budo#42]
This works perfectly:
```javascript
budo( 'src/index.js', {
	port: 3000,
	live: true,
	transform: babelify
} )
```

This correctly serve the file but it does not browserify and es6 the file:
```javascript
budo( './src/index.js', {
	port: 3000,
	live: true,
	transform: babelify
} )
```

**Comment by mattdesl** [comment]
Thanks for the bug report. :+1: 

Absolute and relative paths make this sorta tricky. The following won't work either:

```
../foo/bar.js
./blah/../blah.js
/projects/blah.js
```

For now, you can fix this by specifying a `serve` location:

```js
budo('./src/index.js', { serve: 'bundle.js' })
```

Or via CLI:

```sh
# option A
budo ./src/index.js:bundle.js

# option B
budo ./src/index.js --serve bundle.js
```

--

I'll have to think about a proper fix. Suggestions welcome. I could simply serve the `basename()` of a file instead of the specified path, but it might lead to weird results for some users. For example:

**Comment by mattdesl** [comment]
Ok, added the following:

- `budo ./` and `budo .` resolves to `bundle.js` URL
  - this still needs work though, not sure if watchify supports it yet
- `budo ./foo/bar.js` and `budo foo/bar.js` resolves to `foo/bar.js`
- `budo ../foo/bar.js` resolves to `bar.js`
- `budo /projects/bar.js` resolves to `bar.js`

Going to close for now. If anybody has further ideas on improving this let me know.
