### ISSUE TITLE
Enable LiveReload on non-bundle files

### ISSUE THREAD

**Issue by cvan** [mattdesl/budo#59]
If I have a document that loads the bundle and some other dependent, non-browserified JS file:

```html
<!doctype html>
<html>
  <head>
    <script src="static-file.js"></script>
    <script src="bundle.js"></script>
  </head>
  <body>
  </body>
</html>
```

I want LiveReload to pick up changes to `static-file.js` and reload the page. Can you think of a clever way to do this with budo?

**Comment by cvan** [comment]
Similarly, if the HTML in `<body>` changes, for example, I'd like for the page to be reloaded. I thought LiveReload does that by default - or is the LR watcher looking at when the bundle file changes?

**Comment by mattdesl** [comment]
Are you using CLI or API? 

With `--live` or `live: true`, it should trigger LiveReload events when your HTML files change. The default watch glob is `**/*.{html,css}`.

Regarding the original question - with the API this is already possible. For complex builds I would suggest just using that since it gives you full control over watch/reload events.

`dev.js`

```js
var budo = require('budo') // assumes v5

var app = budo('src/main.js:bundle.js', {
  stream: process.stdout 
})
  // your globs to watch for files
  .watch([ '**/*.{html,css}', 'static-file.js' ])
  // enable LiveReload server
  .live()
  // fire reload as soon as bundle begins updating
  .on('pending', function () {
    app.reload() 
  })
  // also fire reload whenever non-bundle files change
  .on('change', function (ev, file) {
    app.reload(file) 
  })
```

Now run `node dev.js | garnish` and you should be up and running. You can add this as a npm run script for convenience.

Getting this working in CLI would probably involve a new flag, like `--watch`, which replaces the default glob pattern.

e.g.

```sh
budo index.js:bundle.js --live --watch=**/*.{html,css} --watch=static-file.js | garnish
```

**Comment by cvan** [comment]
okay, this all makes sense. feel free to close this issue, if you'd like. I'll just create a new file to use the programmatic API. many thanks for your help. I appreciate it!

**Comment by mattdesl** [comment]
Ok, to keep surface area small and reduce potential complexity/bugs I will not add the `--watch` option for CLI, since the API is working out for you.

However, I'm open to adding it in the future if people feel it would be a useful flag. :smile:
