### ISSUE TITLE
LiveReload injected script often hangs the page on load

### ISSUE THREAD

**Issue by cvan** [mattdesl/budo#79]
Seems to happen in both Chrome and Firefox. Not sure if it's a regression or if it's a problem with [`inject-lr-script`](https://github.com/mattdesl/inject-lr-script).

**Comment by cvan** [comment]
I see this when opening multiple tabs of pages that are served via budo w/ LiveReload:

<img width="787" alt="screenshot 2015-11-14 17 34 34" src="https://cloud.githubusercontent.com/assets/203725/11517879/88184928-9841-11e5-99ab-9ab3a1383bdc.png">
<img width="787" alt="screenshot 2015-11-14 17 34 22" src="https://cloud.githubusercontent.com/assets/203725/11517880/882796f8-9841-11e5-963a-d2c780732006.png">

**Comment by yoshuawuyts** [comment]
Hmh, it might be since it's setting attaching a bunch of event listeners internally. I wrote [inject-lr-script-stream](https://www.npmjs.com/package/inject-lr-script-stream) which _might_ be a way to resolve this, though it may not fit in with the current budo architecture.

**Comment by cvan** [comment]
This prevents me from using LiveReload with more than one tab unfortunately. Just curious if anyone has been able to reproduce this, or if it's just me.

**Comment by mattdesl** [comment]
Hmm never seen this and I've done a bunch of dev with multiple tabs, browsers, and devices open. What version of node are you using? Have you tried removing node_modules and reinstalling?

And yeah, hopefully next week I will have a bit of time to revisit using `filed` instead of `ecstatic`, but it may involve a few other hurdles like directory listings and such.

**Comment by mattdesl** [comment]
This should be fixed in `8.0.0`. Please test and let me know if you see it again. :smile:
