### ISSUE TITLE
Update index file when entry point changes

### ISSUE THREAD

**Issue by rafaelrinaldi** [mattdesl/budo#85]
I got stuck trying to configure `budo` to update my (custom) `index.html` file whenever the specified entry point changes. Can someone help me? Here's my configuration:

```json
"scripts": {
  "server": "budo source/scripts/application.js --live --port 8080 --host localhost --dir ./public --onupdate 'npm run build' | garnish -v",
  "build": "browserify ./source/scripts/application.js -o ./public/assets/scripts/bundle.js -t [ babelify --optional es7 ] -d",
}
```

* I've tried to point the output file to the bundle file using `:` but it didn't work (since it's just a reference to the server);
* The `--onupdate` was a desperate attempt, it doesn't really makes sense;
* If I run `npm run build` it works fine.

Help?

**Comment by mattdesl** [comment]
Hey. I'm not sure exactly what you're trying to achieve. Budo is already doing the `browserify` (build) step internally. The full script might look like this:

```json
"scripts": {
  "server": "budo source/scripts/application.js:assets/scripts/bundle.js --live --port 8080 --dir ./public -- -t [ babelify --optional es7 ] | garnish"
}
```

Now you can start the server and run your site locally. Because of the `:`, instead of serving the local file at `public/assets/scripts/bundle.js`, it will serve the browserified bundle during development.

You still need a `build` step since budo is currently only focused on the development aspect, and not the production/release aspect. 

For example, my typical build + release looks like this with gh-pages and a custom `index.html`:

https://github.com/mattdesl/svg-mesh-3d/blob/4963b8971d9cce74daf562d4f997a2552d9a9def/package.json#L46-L47

**Comment by rafaelrinaldi** [comment]
Hey @mattdesl thanks for the answer. As I've imagined I was trippin'. What you've proposed is exactly what I was looking for.
Having the hability to bundle for production via `budo` would be nice though :smiley: 

Thanks again!
